---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rancher-${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
  labels:
    app: rancher-${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
  template:
    metadata:
      labels:
        app: rancher-${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
    spec:
      containers:
      - name: rancher-${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
        image: ${CICD_EMBED_REGISTRY}/rancher:${CICD_GIT_COMMIT}
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-nodeport-${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rancher-${CICD_GIT_REPO_NAME}-${CICD_GIT_BRANCH}
  sessionAffinity: None
  type: NodePort