---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    field.cattle.io/projectId: ${PROJECT_ID}
  name: rancher-${CICD_GIT_COMMIT}
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: rancher
  namespace: rancher-${CICD_GIT_COMMIT}
  labels:
    app: rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
      - name: rancher
        image: loganhz/rancher:${CICD_GIT_COMMIT}
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-nodeport-${CICD_GIT_COMMIT}
  namespace: rancher-${CICD_GIT_COMMIT}
spec:
  ports:
  - name: https
    protocol: TCP
    targetPort: 443
  - name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: rancher
  sessionAffinity: None
  type: NodePort